# Generated by Django 4.0.6 on 2022-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_userprofuile_currently_hacking_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofuile',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
