# Generated by Django 4.0.6 on 2022-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_userprofuile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofuile',
            name='dob',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
